repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
      - id: autopep8
        language: system
        args: [--global-config=pyproject.toml]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']
      - id: trailing-whitespace
      - id: requirements-txt-fixer

  - repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.3
    hooks:
    - id: autoflake
      language: python
      args: ["--in-place", "--remove-all-unused-imports", "--remove-unused-variables", "--expand-star-imports", "--ignore-init-module-imports"]
      files: \.py$

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)

  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: python -m unittest discover
        language: system
        "types": [python]
        pass_filenames: false
        stages: [commit, push]
